sudo: required

notifications:
  email: false

language: node_js

node_js:
  - "node"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python2.7 pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev clang

before_script:
  - npm install -g gulp
  - npm install

script: gulp